language: ruby
rvm:
  - "2.2.6"
  - "2.3.3"
  - "2.4.0"
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec spec
# workaround for https://github.com/travis-ci/travis-ci/issues/5239:
before_install:
  - gem install bundler
